# Use a imagem oficial do OpenJDK com o JDK como base
FROM openjdk:11

# Copia o arquivo de código-fonte para o contêiner
COPY App.java /app/App.java

# Compile o código-fonte
WORKDIR /app
RUN javac App.java

# Execute o programa Java quando o contêiner for iniciado
CMD ["java", "App"]
