name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

repositories:
  - https://github.com/actions/setup-maven


    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: main
    - name: Setup Maven
      uses: actions/setup-maven@v3
    - name: Build application
      run: mvn clean install

