name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar JDK 20
      uses: actions/setup-java@v2
      with:
        java-version: 20

    - name: Compilar
      run: mvn compile


    - name: Testar
      run: mvn test
