name: Java Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java
        for i in $(seq 9 21); do
          uses: actions/setup-java@v2
          with:
            java-version: $i
          run: java -version
        done
